version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 5
    labels:
      - dependencies
    ignore:
      - dependency-name: "@material-ui/*"
      - dependency-name: "@react*"
      - dependency-name: "@esbuild"
