name: Merge me!

on:
  repository_dispatch:
  workflow_run:
    workflows: ["Remote Dispatch Action Initiator"]
    branches: [main]
    types: 
      - completed
      - requested

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR