name: Merge me!

on:
  workflow_run:
    workflows: ["Remotee Dispatch Action Initiato"]
    branches: [main]
    types: 
      - completed

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR