name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - run: npx @backstage/create-app scaffolded-test-app
      - uses: actions/checkout@v2
        with:
          path: plugins/${{ github.repository }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run tsc
      - run: yarn run lint
      - run: yarn run build
      - run: yarn test
        env:
          CI: true
